apiVersion: v1
kind: ConfigMap
metadata:
  name: jolokia-mapping
  namespace: cicd
data:
  config.yaml: |
    metrics:
      - source:
          mbean: java.lang:type=Memory
          attribute: HeapMemoryUsage
          path: used
        target: java_memory_heap_used
      - source:
          mbean: java.lang:type=Threading
          attribute: ThreadCount
        target: java_threads
      - source:
          mbean: java.lang:type=Runtime
          attribute: Uptime
        target: java_uptime_ms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jolokia-proxy-nginx
  namespace: cicd
data:
  default.conf: |
    server {
      listen 8878;

      # garante que /jolokia redirecione para /jolokia/
      location = /jolokia {
        return 301 /jolokia/;
      }

      # proxy do Jolokia (com barra no final)
      location /jolokia/ {
        proxy_set_header Authorization "Basic YWRtaW46bGludXhAQDEyMw==";
        proxy_pass http://127.0.0.1:8778/jolokia/;
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-mon
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-mon
  template:
    metadata:
      labels:
        app: jenkins-mon
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: mapping
          configMap:
            name: jolokia-mapping
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - name: jolokia-proxy-nginx
          configMap:
            name: jolokia-proxy-nginx
      containers:
        - name: jenkins
          image: esig/jenkins-jolokia:2.528.3
          ports:
            - name: http
              containerPort: 8080
            - name: jolokia
              containerPort: 8778
          env:
            - name: JOLOKIA_USER
              value: "admin"
            - name: JOLOKIA_PASSWORD
              value: "<SUA_SENHA>"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

        - name: jolokia-proxy
          image: nginx:alpine
          ports:
            - name: proxy
              containerPort: 8878
          volumeMounts:
            - name: jolokia-proxy-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

        - name: jolokia-exporter
          image: scalify/jolokia_exporter:latest
          args: ["export","/mapping/config.yaml","http://localhost:8878/jolokia/"]
          ports:
            - name: metrics
              containerPort: 9422
          volumeMounts:
            - name: mapping
              mountPath: /mapping
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-metrics
  namespace: cicd
spec:
  selector:
    app: jenkins-mon
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9422
      targetPort: metrics
  type: ClusterIP
